# Generated by Django 5.0.7 on 2024-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидается'), ('success', 'Успешный'), ('failed', 'Неудачный'), ('refunded', 'Возврат')], default='pending', max_length=9),
        ),
    ]
