# Generated by Django 5.0.7 on 2024-08-24 22:14

import reviews.validators.validators_review
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[reviews.validators.validators_review.validate_profanity]),
        ),
    ]
