# Generated by Django 5.0.7 on 2024-08-24 22:14

import products.validators.validators_price
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[products.validators.validators_price.validate_positive_price]),
        ),
    ]
